apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer-api
  template:
    metadata:
      labels:
        app: tripviewer-api # the label for the pods and the deployments
    spec:
      containers:
      - name: tripviewer-api
        image: registryknz5402.azurecr.io/tripinsights/tripviewer:1.0 # IMPORTANT: update with your own repository
        env:
        - name: USERPROFILE_API_ENDPOINT
          value: http://userprofile-api-service:80
        - name: TRIPS_API_ENDPOINT
          value: http://trips-api-service:80
        resources:
          requests: # minimum resources required
            cpu: 100m
            memory: 128Mi
          limits: # maximum resources allocated
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80 # the application listens to this port
---            
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-api-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: tripviewer-api