apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-api
  namespace: tripinsightsapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi-api
  template:
    metadata:
      labels:
        app: poi-api # the label for the pods and the deployments
    spec:
      containers:
      - name: poi-api
        image: registryknz5402.azurecr.io/tripinsights/poi:1.0 # IMPORTANT: update with your own repository
        ports:
        - containerPort: 80 # the application listens to this port
        env:
        - name: SQL_USER
          value: "from key vault"
        - name: SQL_PASSWORD
          value: "from key vault"
        - name: SQL_SERVER
          value: "from key vault"
        - name: SQL_DBNAME
          value: "from key vault"
        resources:
          requests: # minimum resources required
            cpu: 100m
            memory: 128Mi
          limits: # maximum resources allocated
            cpu: 250m
            memory: 256Mi
        volumeMounts:
          - name: secrets
            mountPath: "/mnt/secrets"
            readOnly: true
      volumes:
      - name: secrets
        csi:
          driver: secrets-store.csi.k8s.io 
          readOnly: true
          volumeAttributes:
            secretProviderClass: "kv-aks-2345"
          nodePublishSecretRef:
            name: secrets-store-creds
---            
apiVersion: v1
kind: Service
metadata:
  name: poi-api-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: poi-api