apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: trip-viewer-ingress
  namespace: tripinsightsweb
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: tripviewer-api-service
          servicePort: 80
        path: /