kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-role
rules:
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-role
rules:
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["get", "list"]