apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: edit-web-pods
  namespace: tripinsightsweb
subjects:
# You can specify more than one "subject"
- kind: Group
  name: 13427e8a-5468-4a9c-838b-7e24e0a9a0e3 # "object id from azure!" 
  namespace: tripinsightsweb
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: edit # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: read-api-pods
  namespace: tripinsightsapi
subjects:
# You can specify more than one "subject"
- kind: Group
  name: 13427e8a-5468-4a9c-838b-7e24e0a9a0e3 # "object id from azure!" 
  namespace: tripinsightsapi
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: view # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: edit-api-pods
  namespace: tripinsightsapi
subjects:
# You can specify more than one "subject"
- kind: Group
  name: 9dc30127-44ba-48ae-b2a5-0bbe09e2da04 # "object id from azure!"
  namespace: tripinsightsapi
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: edit # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: read-web-pods
  namespace: tripinsightsweb
subjects:
# You can specify more than one "subject"
- kind: Group
  name: 9dc30127-44ba-48ae-b2a5-0bbe09e2da04 # "object id from azure!"
  namespace: tripinsightsweb
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: view # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io