apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: kv-aks-2345
  namespace: tripinsightsapi
spec:
  provider: azure
  parameters:
    keyvaultName: "kv-aks-2345"          # the name of the KeyVault
    objects:  |
      array:
        - |
          objectName: SQL-USER
          objectAlias: SQL_USER
          objectType: secret        # object types: secret, key or cert. For Key Vault certificates, refer to https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/getting-certs-and-keys.md for the object type to use
        - |
          objectName: SQL-PASSWORD
          objectAlias: SQL_PASSWORD
          objectType: secret        # object types: secret, key or cert. For Key Vault certificates, refer to https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/getting-certs-and-keys.md for the object type to use
        - |
          objectName: SQL-SERVER
          objectAlias: SQL_SERVER
          objectType: secret        # object types: secret, key or cert. For Key Vault certificates, refer to https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/getting-certs-and-keys.md for the object type to use
        - |
          objectName: SQL-DBNAME
          objectAlias: SQL_DBNAME
          objectType: secret        # object types: secret, key or cert. For Key Vault certificates, refer to https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/getting-certs-and-keys.md for the object type to use

    resourceGroup: "challenge3"                                    # [REQUIRED for version < 0.0.4] the resource group of the KeyVault
    subscriptionId: "ada6875d-873b-40ea-bc55-e9f261d050ad"         # [REQUIRED for version < 0.0.4] the subscription ID of the KeyVault
    tenantId: "68de8f0f-6623-409d-82dd-3e947abdeeb8"               # the tenant ID of the KeyVault